services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  migrator:
    build:
      context: .
      dockerfile: cmd/migrator/Dockerfile
    environment:
      - CONFIG_PATH=/app/migrations.yaml
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./config/migrations.yaml:/app/migrations.yaml
      - ./migrations/:/migrations/
    depends_on:
      - db

volumes:
  pgdata: