env: dev


storage:
  host: db
  port: 5432
  user: postgres
  dbname: l0
  sslmode: disable

kafka:
  brokers: [kafka:9092]
  reader:
    topic: orders
    group_id: app
  writer:
    topic: dlq
    client_id: app